[package]
name = "neuralib-rs-cffi"
description = "Python CFFI bindings for neuralib"

version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "neuralib_rs_cffi"
crate-type = ["cdylib"]

[dependencies]
neuralib = { version = "*", path = "..", features = ["idx"] }
pyo3 = "0.27.0"
